import type { Metadata } from 'next'
import { Inter, Montserrat } from "next/font/google";
import "./globals.css";
import Header from "@/components/ui/header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex h-full flex-col font-Montserrat">
          <Header />
          <div className="flex-1">{children}</div>
        </main>
      </body>
    </html>
  );
}
